#!/usr/bin/env node

const ENCODING = 'UTF8';

var fs = require('fs');
var exec = require('child_process').exec;

var commit_message_path = process.argv[2];
var commit_message = fs.readFileSync( commit_message_path, ENCODING );
exec( 'git symbolic-ref -q HEAD', function( err, branch_path ){
	if( err ) throw err;
	var branch_id = (/\/([^\/-]*)-[^\/]*$/.exec( branch_path ) || [] )[1];
	if( branch_id ){
		var updated_commit_message = '['+ branch_id +'] '+ commit_message;
		fs.writeFileSync( commit_message_path, updated_commit_message, ENCODING );
	}
});